import * as fs from 'fs';
import * as path from 'path';
import { log } from '../logger';

export interface CodeMetrics {
    linesOfCode: number;
    cyclomaticComplexity: number;
    testCoverage: number;
    dependencies: number;
    dependents: number;
    churnRate: number;
    daysSinceLastChange: number;
}

/**
 * NODE SOURCE TYPES
 * - 'codebase': Detected algorithmically from file system
 * - 'agent': Added by AI agent through MCP
 * - 'cluster': Generated by clustering algorithm
 */
export type NodeSource = 'codebase' | 'agent' | 'cluster';

/**
 * ARCHITECTURAL LAYERS
 * Clear categorization of code by its role
 */
export type ArchitecturalLayer = 
    | 'presentation'  // UI Components, Views, Pages
    | 'application'   // Services, Controllers, Use Cases
    | 'domain'        // Models, Entities, Business Logic
    | 'infrastructure'// Config, Database, External Services
    | 'shared';       // Utilities, Helpers, Common code

export class CodeMetricsCalculator {
    /**
     * Calculate comprehensive metrics for a file
     */
    public calculateFileMetrics(filePath: string, content: string): Partial<CodeMetrics> {
        return {
            linesOfCode: this.calculateLOC(content),
            cyclomaticComplexity: this.calculateComplexity(content),
            testCoverage: 0,
            churnRate: 0,
            daysSinceLastChange: this.getDaysSinceLastChange(filePath)
        };
    }

    /**
     * Calculate lines of code (excluding comments and blank lines)
     */
    private calculateLOC(content: string): number {
        const lines = content.split('\n');
        let loc = 0;
        let inBlockComment = false;
        
        for (const line of lines) {
            const trimmed = line.trim();
            if (trimmed.length === 0) continue;
            
            if (trimmed.startsWith('/*')) inBlockComment = true;
            if (inBlockComment) {
                if (trimmed.endsWith('*/') || trimmed.includes('*/')) {
                    inBlockComment = false;
                }
                continue;
            }
            if (trimmed.startsWith('//')) continue;
            
            loc++;
        }
        
        return loc;
    }

    /**
     * Calculate cyclomatic complexity (simplified)
     */
    private calculateComplexity(content: string): number {
        let complexity = 1;
        
        const patterns = [
            /\bif\s*\(/g,
            /\bwhile\s*\(/g,
            /\bfor\s*\(/g,
            /\bcase\s+/g,
            /\bcatch\s*\(/g,
            /\belse\s+if\b/g,
            /&&/g,
            /\|\|/g,
            /\?/g
        ];
        
        patterns.forEach(pattern => {
            const matches = content.match(pattern);
            if (matches) complexity += matches.length;
        });
        
        const functionMatches = content.match(/function\s+\w+|=>\s*{|^[a-zA-Z_]\w+\s*\(/gm);
        if (functionMatches) complexity += functionMatches.length;
        
        return complexity;
    }

    /**
     * Get days since file was last modified
     */
    private getDaysSinceLastChange(filePath: string): number {
        try {
            if (!fs.existsSync(filePath)) return Infinity;
            const stats = fs.statSync(filePath);
            const diffMs = Date.now() - stats.mtime.getTime();
            return Math.floor(diffMs / (1000 * 60 * 60 * 24));
        } catch {
            return Infinity;
        }
    }

    /**
     * DETECT ARCHITECTURAL LAYER
     * 
     * Uses multiple signals to determine the layer:
     * 1. Directory path patterns
     * 2. File name patterns
     * 3. File extension
     * 4. Common naming conventions
     * 
     * Returns a clean architectural layer, NOT 'module'
     */
    public detectLayer(filePath: string): ArchitecturalLayer {
        const lower = filePath.toLowerCase();
        const fileName = path.basename(lower);
        const ext = path.extname(fileName);
        const dirPath = path.dirname(lower);
        const parts = lower.split(/[/\\]/);

        // ═══════════════════════════════════════════════════════════════════════
        // PRESENTATION LAYER (UI, Views, Components)
        // ═══════════════════════════════════════════════════════════════════════
        
        const presentationPatterns = [
            // Directory patterns
            /\/(component|components)\//,
            /\/(view|views)\//,
            /\/(page|pages)\//,
            /\/(screen|screens)\//,
            /\/(layout|layouts)\//,
            /\/(widget|widgets)\//,
            /\/(ui)\//,
            /\/hooks?\//,
            /\/(provider|providers)\//,
            /\/(context|contexts)\//,
            /\/(store|stores)\//,
            /\/(redux|zustand|mobx)\//,
            /\/(atoms?|molecules?|organisms?|templates?)\//,  // Atomic design
            /\/features?\//,
            /\/frontend\//,
            /\/client\//,
            /\/app\//,  // Next.js app directory
            /\/src\/app\//,
            // File patterns
            /\.component\.(ts|tsx|js|jsx)$/,
            /\.view\.(ts|tsx|js|jsx)$/,
            /\.page\.(ts|tsx|js|jsx)$/,
            /\.screen\.(ts|tsx|js|jsx)$/,
            /use[A-Z]\w+\.(ts|tsx|js|jsx)$/,  // Custom hooks
        ];

        // React/Vue/Angular component files
        if (ext === '.tsx' || ext === '.jsx') {
            return 'presentation';
        }
        if (ext === '.vue' || ext === '.svelte') {
            return 'presentation';
        }
        
        for (const pattern of presentationPatterns) {
            if (pattern.test(lower)) return 'presentation';
        }

        // ═══════════════════════════════════════════════════════════════════════
        // APPLICATION LAYER (Services, Controllers, Business Logic)
        // ═══════════════════════════════════════════════════════════════════════
        
        const applicationPatterns = [
            // Directory patterns
            /\/(service|services)\//,
            /\/(controller|controllers)\//,
            /\/(handler|handlers)\//,
            /\/(resolver|resolvers)\//,
            /\/(action|actions)\//,
            /\/(command|commands)\//,
            /\/(query|queries)\//,
            /\/(usecase|usecases|use-case|use-cases)\//,
            /\/(api)\//,
            /\/(route|routes|router|routers)\//,
            /\/(middleware|middlewares)\//,
            /\/(backend)\//,
            /\/(server)\//,
            // File patterns
            /\.service\.(ts|js)$/,
            /\.controller\.(ts|js)$/,
            /\.handler\.(ts|js)$/,
            /\.resolver\.(ts|js)$/,
            /\.action\.(ts|js)$/,
        ];

        for (const pattern of applicationPatterns) {
            if (pattern.test(lower)) return 'application';
        }

        // ═══════════════════════════════════════════════════════════════════════
        // DOMAIN LAYER (Models, Entities, DTOs, Types)
        // ═══════════════════════════════════════════════════════════════════════
        
        const domainPatterns = [
            // Directory patterns
            /\/(model|models)\//,
            /\/(entity|entities)\//,
            /\/(schema|schemas)\//,
            /\/(dto|dtos)\//,
            /\/(type|types)\//,
            /\/(interface|interfaces)\//,
            /\/(domain)\//,
            /\/(value-object|value-objects)\//,
            /\/(aggregate|aggregates)\//,
            // File patterns
            /\.model\.(ts|js)$/,
            /\.entity\.(ts|js)$/,
            /\.schema\.(ts|js)$/,
            /\.dto\.(ts|js)$/,
            /\.type\.(ts|js)$/,
            /\.d\.ts$/,  // TypeScript declaration files
        ];

        for (const pattern of domainPatterns) {
            if (pattern.test(lower)) return 'domain';
        }

        // ═══════════════════════════════════════════════════════════════════════
        // INFRASTRUCTURE LAYER (Config, Database, External)
        // ═══════════════════════════════════════════════════════════════════════
        
        const infrastructurePatterns = [
            // Directory patterns
            /\/(config|configs|configuration)\//,
            /\/(database|db)\//,
            /\/(migration|migrations)\//,
            /\/(seed|seeds|seeder|seeders)\//,
            /\/(repository|repositories)\//,
            /\/(dao)\//,
            /\/(orm)\//,
            /\/(prisma)\//,
            /\/(drizzle)\//,
            /\/(sequelize)\//,
            /\/(mongoose)\//,
            /\/(typeorm)\//,
            /\/(infra|infrastructure)\//,
            /\/(deploy|deployment)\//,
            /\/(docker)\//,
            /\/(k8s|kubernetes)\//,
            /\/(terraform)\//,
            /\/(ci|ci-cd|cicd)\//,
            /\/(scripts)\//,
            /\/(setup)\//,
            /\/(env)\//,
            // File patterns
            /\.config\.(ts|js|json|yaml|yml)$/,
            /\.repository\.(ts|js)$/,
            /config\.(ts|js|json)$/,
            /settings\.(ts|js|json)$/,
            /(docker|Dockerfile)/,
        ];

        // Config files by name
        const configFiles = [
            'package.json', 'tsconfig.json', 'vite.config',
            'webpack.config', 'babel.config', 'jest.config',
            'eslint', '.eslintrc', 'prettier', '.prettierrc',
            'next.config', 'nuxt.config', 'angular.json',
            '.env', 'environment', 'constants'
        ];

        for (const cfg of configFiles) {
            if (fileName.includes(cfg)) return 'infrastructure';
        }

        for (const pattern of infrastructurePatterns) {
            if (pattern.test(lower)) return 'infrastructure';
        }

        // ═══════════════════════════════════════════════════════════════════════
        // SHARED LAYER (Utilities, Helpers, Common)
        // ═══════════════════════════════════════════════════════════════════════
        
        const sharedPatterns = [
            // Directory patterns
            /\/(util|utils|utility|utilities)\//,
            /\/(helper|helpers)\//,
            /\/(lib|libs|library)\//,
            /\/(common)\//,
            /\/(shared)\//,
            /\/(core)\//,
            /\/(base)\//,
            /\/(tools)\//,
            /\/(functions)\//,
            /\/(constants)\//,
            /\/(enums?)\//,
            // File patterns
            /\.util\.(ts|js)$/,
            /\.utils\.(ts|js)$/,
            /\.helper\.(ts|js)$/,
            /\.helpers\.(ts|js)$/,
        ];

        for (const pattern of sharedPatterns) {
            if (pattern.test(lower)) return 'shared';
        }

        // ═══════════════════════════════════════════════════════════════════════
        // FALLBACK: Infer from file extension and common patterns
        // ═══════════════════════════════════════════════════════════════════════
        
        // Test files → shared
        if (fileName.includes('.test.') || fileName.includes('.spec.') || 
            lower.includes('/__tests__/') || lower.includes('/test/') ||
            lower.includes('/tests/')) {
            return 'shared';
        }

        // Index files - determine by parent directory
        if (fileName === 'index.ts' || fileName === 'index.js') {
            // Check parent directory
            const parentDir = parts[parts.length - 2] || '';
            if (/component|view|page|screen|ui/.test(parentDir)) return 'presentation';
            if (/service|controller|api|route/.test(parentDir)) return 'application';
            if (/model|entity|type|schema/.test(parentDir)) return 'domain';
            if (/config|db|migration/.test(parentDir)) return 'infrastructure';
        }

        // Backend file extensions
        if (fileName.endsWith('.go') || fileName.endsWith('.rs') || 
            fileName.endsWith('.java') || fileName.endsWith('.py') ||
            fileName.endsWith('.rb') || fileName.endsWith('.php')) {
            // Likely application layer for most backend files
            return 'application';
        }

        // CSS/SCSS/styles → presentation
        if (ext === '.css' || ext === '.scss' || ext === '.sass' || ext === '.less') {
            return 'presentation';
        }

        // Default: Use the nearest identifiable parent directory
        for (let i = parts.length - 2; i >= 0; i--) {
            const part = parts[i];
            if (/component|view|page|ui|frontend|client/.test(part)) return 'presentation';
            if (/service|controller|api|backend|server/.test(part)) return 'application';
            if (/model|entity|type|domain/.test(part)) return 'domain';
            if (/config|infra|database|deploy/.test(part)) return 'infrastructure';
            if (/util|helper|lib|common|shared/.test(part)) return 'shared';
        }

        // Final fallback - check if it's likely source code
        if (ext === '.ts' || ext === '.js') {
            // Default TypeScript/JavaScript to application layer
            // This is better than "module" because it places them in a known architecture
            return 'application';
        }

        // Truly unknown → shared (safest fallback)
        return 'shared';
    }
}
